version: '3.7'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:7.4-fpm
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html/
    volumes:
      - ./:/var/www/html/
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - your-project

  #Nginx Service
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8001:80"
      - "443:443"
    volumes:
      - ./:/var/www/html/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - your-project

  #MySQL Service
  # db:
  #   image: mysql:5.7.32
  #   container_name: db
  #   restart: unless-stopped
  #   tty: true
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_DATABASE: noyr
  #     MYSQL_ROOT_PASSWORD: noyr
  #     SERVICE_TAGS: dev
  #     SERVICE_NAME: mysql
  #   volumes:
  #     - dbdata:/var/lib/mysql/
  #     - ./mysql/my.cnf:/etc/mysql/my.cnf
  #   networks:
  #     - your-project

#Docker Networks
networks:
  your-project:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local